---
title: "prolific_payment"
author: "Armin"
date: "2025-11-24"
output:
  html_document:
    toc: true
    toc_depth: '5'
    df_print: paged
  html_notebook:
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
  word_document:
    toc: true
    toc_depth: '5'
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Loading packages

```{r, include=FALSE, message=FALSE, warning=FALSE}

library(tidyverse)

```

### Loading data

```{r, include=FALSE, message=FALSE, warning=FALSE}

dat_esm  <- read.csv("esm_pilot_dat.csv", sep = ";")
dat_base <- read.csv("qualtrics_pilot_dat.csv")
dat_prol <- read.csv("prolific_pilot_dat.csv")

```


### Minor cleaning

```{r}

# cleaning and joining esm and baseline data
dat_esm <- dat_esm %>% 
  filter(scheduledBeepId != "-1") %>% # filtering intake rows
  group_by(connectionId) %>% 
  mutate(total_fill = sum(!is.na(anx_som_2_sliderNeutralPos)),
         study_id = toupper(alias)) %>%  # one particpant had lowercase id
  ungroup() %>% 
  filter(!is.na(anx_som_2_sliderNeutralPos)) %>% 
  select("study_id", "total_fill") 


dat_base <- dat_base[-c(1,2), ] %>%  # removing qualtrics metadata rows
  select(study_id, PROLIFIC_PID)

dat_prol <- dat_prol %>% 
  rename(PROLIFIC_PID = Participant.id)

dat <- dat_esm %>% 
  left_join(dat_base, by = "study_id") %>% 
  left_join(dat_prol, by = "PROLIFIC_PID")
  
# calculating bonuses
# based on https://docs.google.com/spreadsheets/d/1KwXkGxeep8NdwvREutBWaeAHLPr17QvEiGWASuHVxnA/edit?gid=0#gid=0

per_survey_bonus <- 0.22    # up to 63 survey fill, beyond that only one time bonus
threshold_fill   <- 64      # one time bonus threshold 
threshold_bonus  <- 4.12    # one time bonus
prolific_sent    <- 3.57    # payment already sent by Prolific

dat <- dat %>%
  mutate(
    beyond_threshold = as.integer(total_fill >= threshold_fill),
    beep_bonus       = pmin(total_fill, threshold_fill - 1) * per_survey_bonus,
    bonus            = beep_bonus + beyond_threshold * threshold_bonus - prolific_sent
  ) %>%
  distinct() %>% 
  select("Submission.id", "bonus")

```


```{r}
tibble(
  total_fill = 80
) %>%
  mutate(
    total_fill_capped = min(c(total_fill, 64)),
    beep_bonus        = total_fill_capped * 0.21,                    # below 80%, USD/survey is 0.17
    threshold_bonus   = ifelse(total_fill >= 64, 4.12, 0),    # 80% of all available surveys (20x4) is 64
    bonus             = beep_bonus + threshold_bonus          # total bonus is the sum of the two
         ) 
```


### Writing .txt for bulk bonus payment

```{r}

# write.csv(dat, "prolific_bonuses.txt", row.names = FALSE, quote = FALSE)

```








